server:
  port: 8090
  servlet:
    context-path: /SSA
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
 #Hibernate Configuration
  jpa:
    properties:
      hibernate:
         format_sql: true
         show_sql: true
